<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Employee.aspx.cs" Inherits="Registration.Movies" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <br />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        DataSourceID="EMPDB" BackColor="White" BorderColor="#CCCCCC" 
        BorderStyle="None" BorderWidth="1px" CellPadding="3" 
        DataKeyNames="Employee_Id">
        <Columns>
            <asp:BoundField DataField="Employee_Id" HeaderText="Employee_Id" 
                SortExpression="Employee_Id" ReadOnly="True" />
            <asp:BoundField DataField="Department_Name" HeaderText="Department_Name" 
                SortExpression="Department_Name" />
            <asp:BoundField DataField="Employee_Name" HeaderText="Employee_Name" 
                SortExpression="Employee_Name" />
            <asp:BoundField DataField="Employee_Salary" HeaderText="Employee_Salary" 
                SortExpression="Employee_Salary" />
        </Columns>
        <FooterStyle BackColor="White" ForeColor="#000066" />
        <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
        <RowStyle ForeColor="#000066" />
        <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#007DBB" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#00547E" />
    </asp:GridView>
    <asp:SqlDataSource ID="EMPDB" runat="server" 
        ConnectionString="<%$ ConnectionStrings:226regiConnectionString %>" 
        SelectCommand="SELECT * FROM [Employee]" UpdateCommand="Update [Employee] Set [Department_Name]=@Department_Name Where [Employee_Id]=@Employee_ID" DeleteCommand="Delete From [Employee] where [Employee_ID]=@Employee_ID"></asp:SqlDataSource>
    <div>
    

    </div>
    <asp:TextBox ID="TextBox1" runat="server" placeholder="ID"></asp:TextBox><asp:TextBox ID="TextBox2"
        runat="server"  placeholder="Type"></asp:TextBox><asp:TextBox ID="TextBox3" runat="server"  placeholder="Name"></asp:TextBox>
            <asp:TextBox ID="TextBox4" runat="server"  placeholder="Salary"></asp:TextBox>
    <asp:Button ID="Button1" runat="server" Text="Add Employee" 
        onclick="Button1_Click" />


   
    &nbsp;&nbsp;&nbsp;
    <br />
    <br />
    <asp:HyperLink ID="HyperLink1" runat="server" EnableViewState="False" 
        NavigateUrl="~/PersonalInfo.aspx">Add Employee Personal Info Here</asp:HyperLink>


   
    </form>
</body>
</html>
